"""The typed contracts of the record (D-66).

pydantic v2 strict-mode models that implement the frozen JSON Schema at `schema/assay/1.0/`. The
schema is the specification; these models are an implementation of it, and a parity gate holds the
two together rather than either one being generated from the other. Owned by P-CONTRACT.
"""

from __future__ import annotations

from .canonical import EXCLUDED_FROM_DIGEST, canonical_bytes, digest, strip_for_digest
from .envelope import RESULT_SCHEMA_VERSION, ResultEnvelope
from .errors import (
    BudgetExceeded,
    CapabilityUnavailable,
    EntryKindEvidenceMissing,
    InternalFailure,
    NumberNotQuantised,
    PendingDecision,
    RecordInvalid,
    RewardLensError,
    SchemaUnknownMajor,
    UsageError,
)
from .models import (
    NO_INTERVAL,
    SCHEMA_URL,
    Absence,
    Assay,
    Attestation,
    CalibrationLink,
    Check,
    Cost,
    Counters,
    Decision,
    DecisionState,
    Detection,
    Embedding,
    Entry,
    EntryProvenance,
    Experiment,
    Finding,
    Hole,
    HoleState,
    Intent,
    JoinRow,
    Kind,
    Measurement,
    Method,
    Power,
    Producer,
    Provenance,
    Rule,
    SandboxTier,
    Scope,
    Section,
    Subject,
    TableRef,
    Uncertainty,
    Verdict,
    Witness,
    absence,
    estimate,
    model_for_def,
)
from .project import OutcomeSpec, ProjectConfig, ResponsesSpec, RewardSpec, TasksSpec
from .quantise import quantise, scale_violations
from .validate import SCHEMA_MAJOR, assay_schema, validate_record

__all__ = [
    "Absence",
    "Assay",
    "Attestation",
    "BudgetExceeded",
    "CalibrationLink",
    "CapabilityUnavailable",
    "Check",
    "Cost",
    "Counters",
    "Decision",
    "DecisionState",
    "Detection",
    "EXCLUDED_FROM_DIGEST",
    "Embedding",
    "Entry",
    "EntryKindEvidenceMissing",
    "EntryProvenance",
    "Experiment",
    "Finding",
    "Hole",
    "HoleState",
    "Intent",
    "InternalFailure",
    "JoinRow",
    "Kind",
    "Measurement",
    "Method",
    "NumberNotQuantised",
    "OutcomeSpec",
    "PendingDecision",
    "Power",
    "Producer",
    "ProjectConfig",
    "Provenance",
    "RESULT_SCHEMA_VERSION",
    "RecordInvalid",
    "ResponsesSpec",
    "ResultEnvelope",
    "RewardLensError",
    "RewardSpec",
    "Rule",
    "SCHEMA_MAJOR",
    "SCHEMA_URL",
    "SandboxTier",
    "SchemaUnknownMajor",
    "Scope",
    "Section",
    "Subject",
    "TableRef",
    "TasksSpec",
    "Uncertainty",
    "NO_INTERVAL",
    "UsageError",
    "Verdict",
    "Witness",
    "absence",
    "assay_schema",
    "canonical_bytes",
    "digest",
    "estimate",
    "model_for_def",
    "quantise",
    "scale_violations",
    "strip_for_digest",
    "validate_record",
]
